### ISSUE TITLE
permission denied 

### ISSUE THREAD

**Issue by karneaud** [agungprsty/sso-with-laravel-passport#1]
Awesome project here and I wanted to use it as a starter kit for a project of mines. I'm getting a lot of permission denied when using docker compose exec. should I try to set the permissions outside or inside the container?

**Comment by agungprsty** [comment]
hi bro! if you encounter permission denied error while running docker command then you need to add it to docker group. You can check this post: https://stackoverflow.com/questions/48957195/how-to-fix-docker-got-permission-denied-issue
